### ISSUE TITLE
Support for file browsing like typescript `import`

### ISSUE THREAD

**Issue by 0hsn** [chkware/vscode-ext#46]
![image](https://user-images.githubusercontent.com/3197377/216805066-24a7564a-8c0f-4683-871c-46cada80d1fa.png)

The above image shows when we add `"./"` with a import a drop-down file name chooser comes in-place.

Implement this feature for testcase.

```yaml
version: default:testcase:**
...
spec:
  execute:
    file: ./file-name.chk # <-- show file chooser drop-down here while editing
...
```
